/**
* ─────────────────────────────────────────────────────────────────────────────────────────────────┐
* SignupTriggerHandler
* @description      This is the Signup Trigger handler class called synchronously 
                    from SignupMasterTrigger.
*				    All the methods needs to be called synchronously from the Signup Trigger
* 				    should be called from here in the before/after insert/update methods.
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @author           Zscaler
* @modifiedBy     
* @maintainedBy     Zscaler
* @version          1.0
* @created          2022-07-04
* @modified       
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @changes
* vX.X              Author Name
* YYYY-MM-DD        Explanation of the change.  Multiple lines can be used to explain the change, but
*                   each line should be indented till left aligned with the previous description text.

VERSION            AUTHOR               DATE            DETAIL              
1.0                Digvijay Singh       21/03/2022      IBA-8286, Creation of the class to add Contact Matching logic.
* ─────────────────────────────────────────────────────────────────────────────────────────────────┘
**/
public class SignupTriggerHandler extends TriggerHandler {
    
    public override void beforeInsert() {

    }
    
    public override void afterInsert() {

    }
    public override void beforeUpdate() {

    }
    public override void afterUpdate() {

    }
    public override void beforeDelete() {

    }
    public override void afterDelete() {

    }
    public override void afterUndelete() {

    }

}