@isTest 
private with sharing class ZScalarConstantsTests {
    
    @isTest
    static void testAllConstants() {
        String Opp_RecType_Name_New_Business_Close = ZScalarConstants.Opp_RecType_Name_New_Business_Close;
        String Opp_RecType_Name_Upsell_Opportunity_Closed = ZScalarConstants.Opp_RecType_Name_Upsell_Opportunity_Closed;
        String Opp_RecType_Name_New_Business = ZScalarConstants.Opp_RecType_Name_New_Business;
        String Opp_RecType_Name_Upsell_Opportunity = ZScalarConstants.Opp_RecType_Name_Upsell_Opportunity;
        String Opp_RecType_Name_Renewal_Opportunity = ZScalarConstants.Opp_RecType_Name_Renewal_Opportunity;
        String Opp_RecType_Id_New_Business_Close = ZScalarConstants.Opp_RecType_Id_New_Business_Close;
        String Opp_RecType_Id_Upsell_Opportunity_Closed = ZScalarConstants.Opp_RecType_Id_Upsell_Opportunity_Closed ;
        String Opp_RecType_Id_New_Business = ZScalarConstants.Opp_RecType_Id_New_Business;
        String Opp_RecType_Id_Upsell_Opportunity = ZScalarConstants.Opp_RecType_Id_Upsell_Opportunity;
        String constaOpp_RecType_Id_Renewal_Opportunitynt1 = ZScalarConstants.Opp_RecType_Id_Renewal_Opportunity;
        
        String Opp_Type_New_Business = ZScalarConstants.Opp_Type_New_Business;
        String Opp_Type_Existing_Customer_Add_On = ZScalarConstants.Opp_Type_Existing_Customer_Add_On;
        String Opp_Type_Existing_Customer_Renewal = ZScalarConstants.Opp_Type_Existing_Customer_Renewal;
        
        String Opp_LeadSource_Advertisement = ZScalarConstants.Opp_LeadSource_Advertisement;
        String Opp_LeadSource_Webinars = ZScalarConstants.Opp_LeadSource_Webinars;
        String Opp_LeadSource_Events = ZScalarConstants.Opp_LeadSource_Events;
        String Opp_LeadSource_External_DM = ZScalarConstants.Opp_LeadSource_External_DM;
        String Opp_LeadSource_List_Import = ZScalarConstants.Opp_LeadSource_List_Import;
        String Opp_LeadSource_Search = ZScalarConstants.Opp_LeadSource_Search;
        String Opp_LeadSource_Paid_Search = ZScalarConstants.Opp_LeadSource_Paid_Search;
        String Opp_LeadSource_Website_Direct = ZScalarConstants.Opp_LeadSource_Website_Direct;
        String Opp_LeadSource_Website_Referral = ZScalarConstants.Opp_LeadSource_Website_Referral;
        String Opp_LeadSource_Social_Media = ZScalarConstants.Opp_LeadSource_Social_Media;
        String Opp_LeadSource_Content_Syndication = ZScalarConstants.Opp_LeadSource_Content_Syndication;
        String Opp_LeadSource_Publisher = ZScalarConstants.Opp_LeadSource_Publisher;
        String Opp_LeadSource_Telemarketing = ZScalarConstants.Opp_LeadSource_Telemarketing;
        String Opp_LeadSource_Marketing_Campaign = ZScalarConstants.Opp_LeadSource_Marketing_Campaign;
        String Opp_LeadSource_Deal_Registration = ZScalarConstants.Opp_LeadSource_Deal_Registration;
        String Opp_LeadSource_Partners = ZScalarConstants.Opp_LeadSource_Partners;
        String Opp_LeadSource_Service_Provider = ZScalarConstants.Opp_LeadSource_Service_Provider;
        String Opp_LeadSource_Sales_Generated = ZScalarConstants.Opp_LeadSource_Sales_Generated;
        
        String Opp_Validation_Stage_6_Technical_Win = ZScalarConstants.Opp_Validation_Stage_6_Technical_Win;
        String Opp_Validation_Stage_7_Technical_Loss = ZScalarConstants.Opp_Validation_Stage_7_Technical_Loss;
        String Opp_Validation_Stage_1_Establishing_Plan_sucess_criteria = ZScalarConstants.Opp_Validation_Stage_1_Establishing_Plan_sucess_criteria;
        String Opp_Validation_Stage_2_Configuration_in_Progress = ZScalarConstants.Opp_Validation_Stage_2_Configuration_in_Progress;
        String Opp_Validation_Stage_3_Detailed_validation_in_progress = ZScalarConstants.Opp_Validation_Stage_3_Detailed_validation_in_progress;
        String Opp_Validation_Stage_4_Delivering_validation_findings_report = ZScalarConstants.Opp_Validation_Stage_4_Delivering_validation_findings_report;
        String Opp_Validation_Stage_8_Not_Required = ZScalarConstants.Opp_Validation_Stage_8_Not_Required;
        String Opp_Validation_Stage_8B_Not_Required_Preferred = ZScalarConstants.Opp_Validation_Stage_8B_Not_Required_Preferred;
        String Opp_Validation_Stage_0_Not_Started = ZScalarConstants.Opp_Validation_Stage_0_Not_Started;
        
        String Value_Creation_Stage_Qualified = ZScalarConstants.Value_Creation_Stage_Qualified;
        String Value_Creation_Stage_Interview_Scheduled = ZScalarConstants.Value_Creation_Stage_Interview_Scheduled;
        String Value_Creation_Stage_Interview_Completed = ZScalarConstants.Value_Creation_Stage_Interview_Completed;
        String Value_Creation_Stage_Model_Completed = ZScalarConstants.Value_Creation_Stage_Model_Completed;
        String Value_Creation_Stage_Output_Presented = ZScalarConstants.Value_Creation_Stage_Output_Presented;
        String Value_Creation_Stage_Stalled = ZScalarConstants.Value_Creation_Stage_Stalled;
        String Value_Creation_Stage_Customer_declined_presentation = ZScalarConstants.Value_Creation_Stage_Customer_declined_presentation;
        String Value_Creation_Stage_RSM_Withdrew_Post_Qualified = ZScalarConstants.Value_Creation_Stage_RSM_Withdrew_Post_Qualified;
    
        String PROJECT_RT_DEPLOYMENT_PROJECT = ZScalarConstants.PROJECT_RT_DEPLOYMENT_PROJECT;
        String PROJECT_RT_ZCP_SPECIALIST_SERVICES = ZScalarConstants.PROJECT_RT_ZCP_SPECIALIST_SERVICES;
    
        String PROJECT_STATUS_COMPLETED = ZScalarConstants.PROJECT_STATUS_COMPLETED;
    
        String PROFILE_SYSTEM_ADMINISTRATOR = ZScalarConstants.PROFILE_SYSTEM_ADMINISTRATOR; 
    }
}